### ISSUE TITLE
Introduce failure

### ISSUE THREAD

**Issue by dalance** [pfnet/rflex#6]
Currently `process` function provides `std::io::Error` only.
So if I want to use rflex as library, I can't get internal error information like `TranslateError`.
Additionally the call of `eprintf` and `std::process::exit` in library can be stopped.

Because rflex is provided as library, it should provide an unified error type and remove the call of `eprintf` and `std::process::exit`.

I recommend to use [failure](https://github.com/rust-lang-nursery/failure) crate to define error type.
The following documents may be helpful.

https://boats.gitlab.io/failure/error-errorkind.html
https://qiita.com/legokichi/items/d76b6aa5dac2ad781bda

**Comment by suma** [comment]
👍  Thank you for your advice and documents.
I can't work immediately, but I want to use `failure` for `process`.

**Comment by suma** [comment]
I tried to use `failure` in this https://github.com/suma/rflex/commit/59876482e5ff8c5a542572f9fda355c6b31e4c62 but I have to work for `PatternError` and `TranslateError`.

**Comment by suma** [comment]
I released v0.5.0 that includes `failure` error handling 🎉

**Comment by dalance** [comment]
Thanks. I'll try it later.
